# Generated by Django 4.2.1 on 2023-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('content', models.TextField(default='', max_length=50000)),
                ('author', models.CharField(default='', max_length=50)),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
