# Generated by Django 4.2.1 on 2023-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
