# Generated by Django 4.2.1 on 2023-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=14)),
                ('email', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
